import { type NextPage } from "next";
import Head from "next/head";
import AuthShowcase from "../components/AuthShowcase";
import TimersList from "../components/TimersList";
import CreateTimer from "../components/CreateTimer";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data } = useSession();

  return (
    <main>
      <Head>
        <title>Karm</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="drawer">
        <input id="my-drawer-4" type="checkbox" className="drawer-toggle" />

        <div className="drawer-content">
          <AuthShowcase />
          {data?.user ? (
            <>
              <TimersList />
              <div className="fixed right-5 bottom-5 md:right-16 md:bottom-16 lg:right-20 lg:bottom-20">
                <label
                  htmlFor="my-drawer-4"
                  className="drawer-button btn-primary btn text-3xl"
                >
                  +
                </label>
              </div>
            </>
          ) : null}
        </div>

        <CreateTimer />
      </div>
    </main>
  );
};

export default Home;
