import { type NextPage } from "next";
import Head from "next/head";
import AuthShowcase from "../components/AuthShowcase";
import TimersList from "../components/TimersList";
import CreateTimer from "../components/CreateTimer";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <AuthShowcase />
        {data?.user ? (
          <>
            <TimersList />
            <CreateTimer />
          </>
        ) : null}
      </main>
    </>
  );
};

export default Home;
